name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run lint
    - run: npm test -- --coverage
    - name: Coverage
      uses: codecov/codecov-action@v3
    - name: Setup node 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm test

    # pretest depends on del-cli which doesn't support node 12, so run manually
    # todo: drop node 12 in next major
    - run: npm run pretest
    - name: Setup node 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm test --ignore-scripts
  create_tgz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node 20
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run build
      - run: npm pack
      - run: mv $(ls | grep .tgz) umzug.tgz
      - uses: actions/upload-artifact@v3
        with:
          name: tarball
          path: umzug.tgz
  test_tgz:
    runs-on: ubuntu-latest
    needs: [create_tgz]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: tarball
      - run: ls
      - name: install tarball in examples directory
        working-directory: examples/0.vanilla
        run: |
          rm -rf ../node_modules
          npm init -y
          npm install ../../umzug.tgz
      - name: run vanilla example
        run: |
          cd examples/0.vanilla
          node migrate up
          node migrate down
          node migrate create --name new-migration.js
          node migrate up
      - name: run vanilla example as ES module
        run: |
          cd examples/0.vanilla
          sed -i "s|const { Umzug, JSONStorage } = require('umzug')|import { Umzug, JSONStorage } from 'umzug'|g" migrate.js
          sed -i "s|exports.migrator = |export const migrator = |g" migrate.js
          sed -i "s|require.main === module|true|g" migrate.js
          sed -i "s|__dirname|'$(pwd)'|g" migrate.js
          sed -i "s|exports.migrator|migrator|g" migrate.js
          mv migrate.js migrate.mjs
          cat migrate.mjs
          node migrate.mjs up
          node migrate.mjs down
          node migrate.mjs create --name other-new-migration.mjs
          node migrate.mjs up
      - run: ls -R
